unittest_isolation = executable('yanet-dataplane-unittest-isolation',
                               ['../isolation.cpp',
                                '../isolation_worker.cpp',
                                '../../dataplane.cpp',
                                '../../rteflow.cpp',
                                '../../report.cpp',
                                '../../controlplane.cpp',
                                '../../dregress.cpp',
                                '../../fragmentation.cpp',
                                '../../bus.cpp',
                                '../../memory_manager.cpp',
                                '../../neighbor.cpp',
                                '../../netlink.cpp'],
                               include_directories: yanet_rootdir,
                               dependencies: dependencies + dependency('libnl-route-3.0'),
                               cpp_args: cpp_args_append + ['-mlzcnt', '-ffunction-sections', '-fdata-sections'],
                               link_args: ['-Wl,--gc-sections',
                                           '-Wl,--wrap=numa_node_of_cpu',
                                           '-Wl,--wrap=rte_flow_create'],
                               override_options: 'b_lto=false')
test('controlplane-isolation', unittest_isolation, timeout: 180, protocol: 'gtest')
