FROM ubuntu:18.04 AS base

RUN apt-get update && apt-get upgrade -y

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    git \
    autoconf \
    automake \
    libtool \
    build-essential \
    ca-certificates

RUN mkdir -p /project
WORKDIR /project


# JSON
ENV NLOHMANN_JSON_VERSION 3.11.2

WORKDIR /project
RUN curl -L https://github.com/nlohmann/json/releases/download/v${NLOHMANN_JSON_VERSION}/json.hpp -o json.hpp
RUN mkdir -p /target/include/nlohmann && \
    cp -v json.hpp /target/include/nlohmann/


# protobuf
ENV PROTOBUF_VERSION 21.12

WORKDIR /project
RUN git clone -b v${PROTOBUF_VERSION} https://github.com/protocolbuffers/protobuf

WORKDIR /project/protobuf
RUN git log -3
RUN git submodule update --init --recursive
RUN ./autogen.sh && \
    ./configure --prefix=/target "CFLAGS=-fPIC" "CXXFLAGS=-fPIC"
RUN make -j
RUN make install

# bison
ENV BISON_VERSION 3.3.2

WORKDIR /project
RUN curl http://ftp.gnu.org/gnu/bison/bison-${BISON_VERSION}.tar.gz -o bison.tar.gz
RUN mkdir bison && \
    tar -xf bison.tar.gz -C bison --strip-components=1

WORKDIR /project/bison
RUN ./configure --prefix=/usr
RUN make -j
RUN make prefix=/target install

FROM ubuntu:18.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    meson \
    ninja-build \
    pkg-config \
    git \
    libnuma-dev \
    libnl-route-3-dev \
    libibverbs-dev \
    libpcap-dev \
    libsystemd-dev \
    libyaml-cpp-dev \
    libgtest-dev \
    flex \
    libfl-dev \
    netbase \
    gdb \
    vim \
    devscripts \
    debhelper \
    dupload \
    python3-pyelftools \
    python3-pip \
    curl

RUN python3 -m pip install meson

RUN apt remove -y libprotobuf-dev

COPY --from=base /target/ /usr/

# cmake
RUN curl https://cmake.org/files/v3.16/cmake-3.16.7-Linux-x86_64.tar.gz -o cmake-3.16.7-Linux-x86_64.tar.gz
RUN tar zxvf cmake-3.16.7-Linux-x86_64.tar.gz
RUN mv cmake-3.16.7-Linux-x86_64     /opt/cmake-3.16.7
RUN ln -sf  /opt/cmake-3.16.7/bin/*    /usr/bin

WORKDIR /project
