FROM ubuntu:18.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    meson \
    ninja-build \
    pkg-config \
    git \
    libnuma-dev \
    libibverbs-dev \
    libpcap-dev \
    libsystemd-dev \
    libyaml-cpp-dev \
    libgtest-dev \
    flex \
    libfl-dev \
    netbase \
    gdb \
    vim \
    devscripts \
    debhelper \
    dupload \
    python3-pyelftools \
    python3-pip \
    protobuf-compiler \
    libprotobuf-dev \
    bison

RUN python3 -m pip install meson

WORKDIR /project
