#ifndef _RTE_CONFIG_APPEND_H_
#define _RTE_CONFIG_APPEND_H_

#undef RTE_PKTMBUF_HEADROOM
#define RTE_PKTMBUF_HEADROOM 256

#undef RTE_MAX_MEM_MB_PER_TYPE
#define RTE_MAX_MEM_MB_PER_TYPE 131072

#undef RTE_ETHDEV_RXTX_CALLBACKS

#endif /* _RTE_CONFIG_APPEND_H_ */
