
#define CONFIG_YADECAP_AUTOTEST

#ifdef YANET_CONFIG_BALANCER_REALS_SIZE
#undef YANET_CONFIG_BALANCER_REALS_SIZE
#endif
#define YANET_CONFIG_BALANCER_REALS_SIZE (1024)

#ifdef CONFIG_YADECAP_GB_ECMP_SIZE
#undef CONFIG_YADECAP_GB_ECMP_SIZE
#endif
#define CONFIG_YADECAP_GB_ECMP_SIZE (15)

#ifdef YANET_CONFIG_ROUTE_TUNNEL_ECMP_SIZE
#undef YANET_CONFIG_ROUTE_TUNNEL_ECMP_SIZE
#endif
#define YANET_CONFIG_ROUTE_TUNNEL_ECMP_SIZE (32)
