name: Packages

on:
  push:
    branches: ["*", "deb-package"]

jobs:
  build-debian-package-jammy:
    name: build (Ubuntu 22.04)
    runs-on: ubuntu-latest
    container:
      image: yanetplatform/builder-lite
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: |
          export YANET_VERSION=v0.1
          export YANET_VERSION=${YANET_VERSION#v}
          export YANET_VERSION_MAJOR=${YANET_VERSION%.*}
          export YANET_VERSION_MINOR=${YANET_VERSION#*.}
          export YANET_VERSION_REVISION=${{github.run_number}}
          export YANET_VERSION_HASH=${{github.sha}}
          export YANET_VERSION_CUSTOM=stable
          dpkg-buildpackage -b
      - uses: actions/upload-artifact@v3
        with:
          name: target_debian-22.04
          path: /__w/yanet/yanet*.deb

  build-debian-package-bionic:
    name: build (Ubuntu 18.04)
    runs-on: ubuntu-latest
    container:
      image: yanetplatform/builder_ubuntu18.04-lite
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - run: |
          export YANET_VERSION=v0.1
          export YANET_VERSION=${YANET_VERSION#v}
          export YANET_VERSION_MAJOR=${YANET_VERSION%.*}
          export YANET_VERSION_MINOR=${YANET_VERSION#*.}
          export YANET_VERSION_REVISION=${{github.run_number}}
          export YANET_VERSION_HASH=${{github.sha}}
          export YANET_VERSION_CUSTOM=stable
          dpkg-buildpackage -b
      - uses: actions/upload-artifact@v3
        with:
          name: target_debian-18.04
          path: /__w/yanet/yanet*.deb
