name: Packages

on:
  push:
    branches: ["*", "deb-package"]

jobs:
  build-ubuntu-22-04:
    name: build (Ubuntu 22.04)
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: |
          apt-get update
          apt-get install -y --no-install-recommends \
          build-essential \
          meson \
          ninja-build \
          pkg-config \
          git \
          libnuma-dev \
          libibverbs-dev \
          libpcap-dev \
          libsystemd-dev \
          libyaml-cpp-dev \
          libgtest-dev \
          flex \
          libfl-dev \
          netbase \
          devscripts \
          debhelper \
          dupload \
          python3-pyelftools \
          python3-pip \
          protobuf-compiler \
          libprotobuf-dev \
          bison \
          debhelper-compat
          export YANET_VERSION=v0.1
          export YANET_VERSION=${YANET_VERSION#v}
          export YANET_VERSION_MAJOR=${YANET_VERSION%.*}
          export YANET_VERSION_MINOR=${YANET_VERSION#*.}
          export YANET_VERSION_REVISION=${{github.run_number}}
          export YANET_VERSION_HASH=${{github.sha}}
          export YANET_VERSION_CUSTOM=stable
          dpkg-buildpackage -b
      - uses: actions/upload-artifact@v3
        with:
          name: target_debian-22.04
          path: /__w/yanet/yanet*.deb

  build-ubuntu-18-04:
    name: build (Ubuntu 18.04)
    runs-on: ubuntu-latest
    container:
      image: ubuntu:18.04
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - run: |
          apt-get update
          apt-get install -y --no-install-recommends \
          build-essential \
          ninja-build \
          pkg-config \
          git \
          libnuma-dev \
          libibverbs-dev \
          libpcap-dev \
          libsystemd-dev \
          libyaml-cpp-dev \
          libgtest-dev \
          flex \
          libfl-dev \
          netbase \
          devscripts \
          debhelper \
          dupload \
          python3-pyelftools \
          python3-pip \
          protobuf-compiler \
          libprotobuf-dev \
          bison \
          debhelper-compat
          python3 -m pip install meson
          export YANET_VERSION=v0.1
          export YANET_VERSION=${YANET_VERSION#v}
          export YANET_VERSION_MAJOR=${YANET_VERSION%.*}
          export YANET_VERSION_MINOR=${YANET_VERSION#*.}
          export YANET_VERSION_REVISION=${{github.run_number}}
          export YANET_VERSION_HASH=${{github.sha}}
          export YANET_VERSION_CUSTOM=stable
          dpkg-buildpackage -b
      - uses: actions/upload-artifact@v3
        with:
          name: target_debian-18.04
          path: /__w/yanet/yanet*.deb
